### ISSUE TITLE
run from subfolder

### ISSUE THREAD

**Issue by akwatra** [SherifAbdlNaby/Ciro-PHP-Framework#3]
can we run this in shared hosting subfolder structure?

I tried with localhost 
htdocs/ciro <-- unzip all project files 
but not running 

How to resolve this

**Comment by SherifAbdlNaby** [comment]
I haven't actually tried shared hosting subfolder structure.
at the moment to use the framework it needs to be unzipped in htdocs/, however you can put the files in a subfolder/s and use .htacess at htdocs/ to redirect to the subfolder accordingly.
